"""The integration contract: what an agent is, and what it is authorised to do.

Every other package reads this one. It depends on nothing else in the tree, and in
particular `targets/` implements it rather than owning it, so `judge/` never has to import
from `targets/` to know what a violation is.
"""

from agentred.spec.loader import SpecError, load_spec, load_spec_dir
from agentred.spec.models import (
    AgentConfig,
    AgentPolicy,
    AgentSpec,
    AnyBound,
    Bound,
    CitationRequirement,
    Consequence,
    CumulativeBound,
    DataScope,
    DataSource,
    Engine,
    EnumeratedBound,
    IdempotencyRequirement,
    ImputedBound,
    MatchingBound,
    NumericBound,
    Obligation,
    ObligationKind,
    OutboundRule,
    Precondition,
    Provenance,
    RelationalBound,
    ResultCondition,
    ResultReference,
    Subject,
    ToolDeclaration,
    VersionTuple,
)

__all__ = [
    "AgentConfig",
    "AgentPolicy",
    "AgentSpec",
    "AnyBound",
    "Bound",
    "CitationRequirement",
    "Consequence",
    "CumulativeBound",
    "DataScope",
    "DataSource",
    "Engine",
    "EnumeratedBound",
    "IdempotencyRequirement",
    "ImputedBound",
    "MatchingBound",
    "NumericBound",
    "Obligation",
    "ObligationKind",
    "OutboundRule",
    "Precondition",
    "Provenance",
    "RelationalBound",
    "ResultCondition",
    "ResultReference",
    "SpecError",
    "Subject",
    "ToolDeclaration",
    "VersionTuple",
    "load_spec",
    "load_spec_dir",
]
